### ISSUE TITLE
Add grafana dashboards for prometheus operator

### ISSUE THREAD

**Issue by mfilotto** [google-cloud-tools/kube-eagle-helm-chart#16]
It would be nice if grafana dasboards could be added though ConfigMap as it is done in https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by chevalier-m** [comment]
I would like to upvote this feature.
I'm currently implementing and deploying in a production ready cluster prometheus and the whole monitoring stack, this would be really helpful.
I won't have time in the near future to handle it, but if we decide kube-eagle is our way to go, I would potentially make a PR that would solve the issue.

**Comment by weeco** [comment]
I'd accept a PR for this, but I don't have intentions to submit the PR myself. I can help by answering questions though.

**Comment by botzill** [comment]
I solve this by adding the following config into prom-operator:

```
grafana:
  ...
  dashboards:
    public:
      kube-eagle:
        gnetId: 9871
        revision: 2
        datasource: Prometheus
```

So, it will automatically take the dashboard from https://grafana.com/dashboards.
