### ISSUE TITLE
add securityContext to helm chart

### ISSUE THREAD

**Issue by davidkarlsen** [google-cloud-tools/kube-eagle-helm-chart#6]
Can you add a securityContext for the container (and possibly also the pod) with minimal access - so that it can be deployed with a strict PSP.

Without it I get:
```
state:
        waiting:
          message: container has runAsNonRoot and image will run as root
          reason: CreateContainerConfigError

```
